# Generated by Django 5.1.7 on 2025-06-25 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('orders', '0001_initial'),
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscribe.subscribe'),
        ),
        migrations.AddField(
            model_name='orders',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.account'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.orders'),
        ),
    ]
