# Generated by Django 5.1.7 on 2025-05-14 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_id', models.IntegerField()),
                ('target_type', models.CharField(choices=[('BOARD', '게시글'), ('COMMENT', '댓글')], max_length=20)),
                ('reason_type', models.CharField(choices=[('SPAM', '불법광고'), ('ABUSE', '욕설/인신공격'), ('REPEAT', '도배성글/댓글반복'), ('PRIVACY', '개인정보노출/사생활침해'), ('SEXUAL', '음란성/선정성'), ('FALSE_INFO', '허위정보/가짜리뷰'), ('DISCRIMINATION', '차별/혐오표현'), ('ETC', '기타부적절한행위')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_processed', to='account.account')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'db_table': 'report',
            },
        ),
    ]
