# Generated by Django 5.1.7 on 2025-06-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='content_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
