# Generated by Django 5.1.7 on 2025-05-14 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('SUBSCRIBE', 'Subscribe')], default='USER', max_length=64)),
            ],
            options={
                'db_table': 'account_role_type',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('account_register', models.DateTimeField(auto_now_add=True)),
                ('account_used_date', models.DateTimeField(auto_now=True)),
                ('account_path', models.CharField(blank=True, choices=[('kakao', 'Kakao'), ('naver', 'Naver'), ('google', 'Google'), ('meta', 'Meta'), ('us', 'Us')], max_length=10, null=True)),
                ('account_status', models.IntegerField(default=0)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True, null=True)),
                ('banned_reason', models.TextField(blank=True, null=True)),
                ('role_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountroletype')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
