# Generated by Django 5.1.7 on 2025-05-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviewCount', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('closed', models.CharField(default=False, max_length=255, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
    ]
