# Generated by Django 5.1.7 on 2025-05-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_scrap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountscrap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
