services:
  django:
    container_name: django
    image: ghcr.io/${GITHUB_ACTOR}/backend-deploy-server:latest
    command: /app/wait-for-it.sh db:3306 -t 15 -- sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py load_csv && python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=snack.settings
      - SECRET_KEY=${SECRET_KEY}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=3306
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - KAKAO_LOGIN_URL=${KAKAO_LOGIN_URL}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - KAKAO_TOKEN_REQUEST_URI=${KAKAO_TOKEN_REQUEST_URI}
      - KAKAO_USER_INFO_REQUEST_URI=${KAKAO_USER_INFO_REQUEST_URI}
      - NAVER_LOGIN_URL=${NAVER_LOGIN_URL}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - NAVER_REDIRECT_URI=${NAVER_REDIRECT_URI}
      - NAVER_TOKEN_REQUEST_URI=${NAVER_TOKEN_REQUEST_URI}
      - NAVER_USER_INFO_REQUEST_URI=${NAVER_USER_INFO_REQUEST_URI}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - TOSS_PAYMENTS_BASE_URL=${TOSS_PAYMENTS_BASE_URL}
      - TOSS_PAYMENTS_SECRET_KEY=${TOSS_PAYMENTS_SECRET_KEY}
      - GOOGLE_LOGIN_URL=${GOOGLE_LOGIN_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET= ${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI= ${GOOGLE_REDIRECT_URI}
      - GOOGLE_TOKEN_REQUEST_URI= ${GOOGLE_TOKEN_REQUEST_URI}
      - GOOGLE_USER_INFO_REQUEST_URI= ${GOOGLE_USER_INFO_REQUEST_URI}
      - GITHUB_LOGIN_URL= ${GITHUB_LOGIN_URL}
      - GITHUB_CLIENT_ID= ${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET= ${GITHUB_CLIENT_SECRET}
      - GITHUB_REDIRECT_URI= ${GITHUB_REDIRECT_URI}
      - GITHUB_TOKEN_REQUEST_URI= ${GITHUB_TOKEN_REQUEST_URI}
      - GITHUB_USER_INFO_REQUEST_URI= ${GITHUB_USER_INFO_REQUEST_URI}
      - GITHUB_ADMIN_CODE= ${GITHUB_ADMIN_CODE}
      - GITHUB_SCOPE= ${GITHUB_SCOPE}
      - GITHUB_ACCESS_TOKEN= ${GITHUB_ACCESS_TOKEN}
      - META_LOGIN_URL= ${META_LOGIN_URL}
      - META_CLIENT_ID= ${META_CLIENT_ID}
      - META_CLIENT_SECRET= ${META_CLIENT_SECRET}
      - META_REDIRECT_URI= ${META_REDIRECT_URI}
      - META_TOKEN_REQUEST_URI= ${META_TOKEN_REQUEST_URI}
      - META_USER_INFO_REQUEST_URI= ${META_USER_INFO_REQUEST_URI}



    networks:
      - app

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - app

volumes:
  db_data:
  redis_data:
  app:

networks:
  app:
    external: true